### PR TITLE
Lesson 3.1

### PR DESCRIPTION
**Pull request by yaninacruz**

### CODE REVIEW

**Comment by Jkuffler** [comment]
It appears you may want to rework the Route configuration. If I have more time later I might be able to fully debug the issue with why the form isn't showing up.
The only way I can get the form to render: if I rearrange the paths inside the Routes that are set up in App.js; however, this only gets either one or the other to render (list or form).
I'll leave you to work it out for now. It's pretty close to working! Remember to reach out in the Slack channel for extra guidance. The two options that come to mind that I would try: rearranging the JSX to contain the TodoList and the TodoForm or creating a component TodoContainer to encapsulate the form and the list together.

**Comment by yaninacruz** [comment]
> It appears you may want to rework the Route configuration. If I have more time later I might be able to fully debug the issue with why the form isn't showing up.
> The only way I can get the form to render: if I rearrange the paths inside the Routes that are set up in App.js; however, this only gets either one or the other to render (list or form).
> I'll leave you to work it out for now. It's pretty close to working! Remember to reach out in the Slack channel for extra guidance. The two options that come to mind that I would try: rearranging the JSX to contain the TodoList and the TodoForm or creating a component TodoContainer to encapsulate the form and the list together.

Thank you Jason! I will work on it tonight. Once fixed should I message you with the new pull request or resubmit the assignment? Thank you!

**Comment by Jkuffler** [comment]
Thanks for checking. If you resubmit, then I can mark it as completed. Thank you for the quick response today 👍 You've definitely got this!

**Comment by yaninacruz** [comment]
> Thanks for checking. If you resubmit, then I can mark it as completed. Thank you for the quick response today 👍 You've definitely got this!

Thank you! I will do that.

**Pull request merged**
